//RTL Wrapper auto-generated by Vivado HLS.
#include "advios.h"


SC_MODULE(advios_rtl_wrapper) {

    //ESL interface.

    sc_in<bool > clk;

    sc_in<bool > reset;

    sc_in<sc_uint<4> > ctrl;

    sc_in<sc_uint<4> > inSwitch;

    sc_out<sc_uint<4> > outLeds;

    //RTL interface signals.


    sc_signal<sc_logic > rtl_reset;

    sc_signal<sc_lv<4> > rtl_ctrl;

    sc_signal<sc_lv<4> > rtl_inSwitch;

    sc_signal<sc_lv<4> > rtl_outLeds;


advios* advios_inst;

    SC_CTOR(advios_rtl_wrapper) { 

        advios_inst = new advios("advios_rtl_inst");


        initInstances(advios_inst);

        SC_METHOD(signal_connection);

        sensitive<<clk<<reset<<ctrl<<inSwitch<<rtl_outLeds;

    }

    ~advios_rtl_wrapper() {

    delete advios_inst;

    }

    void initInstances(advios * advios_inst) {

        //The RTL model.

        
        advios_inst->clk(clk);

        advios_inst->reset(rtl_reset);

        advios_inst->ctrl(rtl_ctrl);

        advios_inst->inSwitch(rtl_inSwitch);

        advios_inst->outLeds(rtl_outLeds);

    }


    void signal_connection() {


        rtl_reset.write((sc_logic)(reset.read()));

        rtl_ctrl.write((sc_lv<4>)(ctrl.read()));

        rtl_inSwitch.write((sc_lv<4>)(inSwitch.read()));

        outLeds.write((sc_lv<4>)(rtl_outLeds.read()));


    }

};
