# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.2
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================

set ::env(PATH) "$::env(PATH);C:/Xilinx/Vivado_HLS/2017.2/win64/tools/fpo_v7_0"

set ::env(PATH) "$::env(PATH);C:/Xilinx/Vivado_HLS/2017.2/win64/tools/opencv"
set ::env(PATH) "$::env(PATH);C:/Xilinx/Vivado_HLS/2017.2/win64/tools/fft_v9_0"
set ::env(PATH) "$::env(PATH);C:/Xilinx/Vivado_HLS/2017.2/win64/tools/fir_v7_0"
set ::env(PATH) "$::env(PATH);C:/Xilinx/Vivado_HLS/2017.2/win64/tools/dds_v6_0"

source check_sim.tcl


# --> systemc simulation

ap_puts_info "COSIM" 11 "Starting SystemC simulation ..."

cd ../systemc

# remove hdltvin&hdltvout in tv dir
file delete -force [file join "../tv" advios.hdltvin.dat]
file delete -force [file join "../tv" advios.hdltvout.dat]

set ::env(AP_WRITE_TV) "on"

file delete -force  "err.log"

if {![file exists cosim.sc.exe]} {
	ap_puts_err "COSIM" 321 " EXE file generate failed, please re-run cosim."
	return -code error -errorcode $::errorCode
}

set ret [catch {eval exec ./cosim.sc.exe | tee temp1.log >&@ stdout} err]

if {$ret == 1} {
	ap_puts_err "COSIM" 344 "Rtl simulation failed."
	return -code error -errorcode $::errorCode
}

if {[file isfile advios.hdltvin.dat]} {
	file copy -force advios.hdltvin.dat [file join "../tv" advios.hdltvin.dat]
}
if {[file isfile advios.hdltvout.dat]} {
	file copy -force advios.hdltvout.dat [file join "../tv" advios.hdltvout.dat]
}

sc_sim_check $ret $err "temp1.log"

# --> vhdl simulation

ap_puts_info "COSIM" 322 "Starting VHDL simulation..."

ap_puts_info "COSIM" 15 "Starting XSIM ..."

cd ../vhdl

if {![file exists [file join "../tv" advios.hdltvin.dat]]} {
	ap_puts_err "COSIM" 332 "Test Vector advios.hdltvin.dat in /tv dir doesn't exist."
	return -code error -errorcode $::errorCode
}

file copy -force [file join "../tv" advios.hdltvin.dat] advios.hdltvin.dat

file copy -force [file join "../tv" advios.hdltvout.dat] advios.hdltvout.dat

file delete -force ".exit.err"
file delete -force ".aesl_error"
file delete -force "err.log"

if {[file isfile run_xsim.bat]} {
	set ret [catch {eval exec "./run_xsim.bat | tee temp2.log" >&@ stdout} err]
}
